### ISSUE TITLE
Soundfont list file handling problems (System.IO.IOException, System.ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by minelolpride** [KaleidonKep99/OmniMIDI#186]
**Problem**
When adding a new file to the "Shared List" soundfont list, the configurator complains that the file **%appdata%\Common SoundFonts\SoundFontList.csflist** is being used by another process. This does not happen 100% of the time, and not only by this event. More details at the bottom.

**Steps to reproduce**
1. Open the "Shared List" soundfont list
2. Add a new soundfont into the list

**Expected behavior**
The soundfont gets added to the list, and if the option is enabled, the list will reload and start playing with the new soundfont. Additionally, when switching between lists, they should be as the user left them.

**Screenshots/Videos**
Here are the traces for both errors
When the soundfont list is inaccessible (from the JIT error box)
```
************** Exception Text **************
System.IO.IOException: The process cannot access the file 'C:\Users\M-3570\AppData\Roaming\Common SoundFonts\SoundFontList.csflist' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at OmniMIDIConfigurator.SoundFontListExtension.SaveList(ListViewEx& List, Int32 SelectedList, String SavePath)
   at OmniMIDIConfigurator.SoundFontListEditor.Lis_ItemChecked(Object sender, ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at OmniMIDIConfigurator.ListViewEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
When prompted to regenerate the list.
![image](https://user-images.githubusercontent.com/16008698/115136559-c2d10880-9fdd-11eb-9a85-c89688f216a8.png)

**Environment**
 - Operating system: Windows 10 Home Version 20H2 (Build 19042.928)
 - CPU: AMD Ryzen 3700X @ 4.2 GHz
 - RAM: 64GB DDR4 2666MHz
 - MIDI application: OmniMIDI (Version 13.8.2.0)
 - Version of the driver: 13.8.2.0

**Additional context**
Note 1: There is a rare chance that this error does not initially occur at all when adding a new soundfont. This error also does not occur often for soundfonts already in the list that are re-added.

Note 2: When this error happens, you can hit "Continue" and it will continue to function as normal sometimes. The occasions where this does not work, OmniMIDI may complain that the soundfont list is inaccessible and prompt to regenerate the list. You *should* be able to click "No" and continue as normal, I have not had it freak out over that yet.

Note 3: After getting this error, if you switch the list shown to a different one then switch back, the error will trigger again, disabling whatever soundfonts you added. This will not repeat until you add another new soundfont and trigger the error that way again. This particular scenario does not always reproduce in my testing, but it happens more than half the time it seems.

Note 4: This error does not get triggered by adding soundfonts to the other lists. However, if you add sone soundfonts to the shared list and switch to a different list, and add some soundfonts, then switch back to the main list, the changes to the shared list will be **wiped out**, leaving either what was there to begin with or only the first soundfont in the list, then prompting to regenerate as per Note 2 (without the JIT error popup though). If you build the soundfont list with a bunch of soundfonts from nothing, then encounter this issue, you will be left with likely only the first soundfont, but sometimes you can have 2 stick around. The other lists are left intact despite all this. If you have soundfonts already present in other lists (for example, List 2), you can add soundfonts without encountering this error, however if you switch away and then back to the shared list, your changes (or list) are still wiped out.

Reinstalling the driver hasn't fixed this one, so maybe it's not just a me thing this time? I hope.

**Comment by minelolpride** [comment]
After posting this I found somehow that Xing out the error window seems to result in all the list items showing up again. Maybe the list isn't getting wiped out after all?

Edit: Only sometimes.

**Comment by KaleidonKep99** [comment]
I'll look into it once I have a working computer!

**Comment by KaleidonKep99** [comment]
I'll take a look at it now.

**Comment by KaleidonKep99** [comment]
Added workaround in 13.8.3.
