### ISSUE TITLE
KS Crashed

### ISSUE THREAD

**Issue by knock2one** [KaleidonKep99/OmniMIDI#71]
When deleting soundfonts that were missing, KS crashed and this is the error:
![image](https://user-images.githubusercontent.com/22779352/29007938-c9561ff4-7adb-11e7-860e-c7636fa71319.png)

"See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at KeppySynthConfigurator.KeppySynthConfiguratorMain.Lis_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)"
I don't know what happened

**Comment by KaleidonKep99** [comment]
Fixed as of [version 4.3.3.5](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.3.3.5).
